No onboarding page
Code-For-Chicago/Voma-frontend pull request #12
Opened 2021-07-26 17:58 UTC by daleinen7

[Ticket](https://trello.com/c/K0zpjwWg/170-voma-create-no-onboarding-page)

2021-07-26 20:08 UTC, jrapala requested changes

2021-07-26 20:08 UTC, jrapala commented on src/pages/NoOnboarding.jsx
> +    <StyledDiv>
Let's use a `<section>` instead

2021-07-26 20:08 UTC, jrapala commented on src/pages/NoOnboarding.jsx
> +        attened Onboarding Night yet then register and attened one through our Meetup Page: &nbsp;
A couple of typos
Should be "attended" and "attend"

2021-07-30 13:36 UTC, jrapala requested changes

2021-07-30 13:36 UTC, jrapala commented on src/pages/NoOnboarding.jsx
> +        <button type="button">Start Over</button>
This isn't exactly valid HTML [Spec](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element)
Can you style the Link to look like a button instead?

2021-08-03 17:54 UTC, jrapala approved these changes

2021-08-03 22:48 UTC, Donovon approved these changes

2021-08-04 16:44 UTC, merged